// Token emoji mapping for visual alerts
export const TOKEN_EMOJI_MAP: Record<string, string> = {
  BTC: '🪙',
  ETH: '💎',
  BNB: '🔶',
  SOL: '🔵',
  USDT: '💵',
  USDC: '💵',
  DOGE: '🐕',
  XRP: '💧',
  ADA: '🔷',
  MATIC: '🟣',
  DOT: '⚫',
  AVAX: '🔴',
  LINK: '🔗',
  UNI: '🦄',
  AAVE: '👻',
  SAND: '🏖️',
  MANA: '🌐',
  SHIB: '🐕',
  PEPE: '🐸',
  FLOKI: '🐕',
  LTC: '🪙',
  XLM: '⭐',
  TRX: '🔴',
  ETC: '💠',
  XMR: '🔒',
  DASH: '💨',
  ZEC: '⚡',
  ATOM: '⚛️',
  NEAR: '🌐',
  ALGO: '🔷',
  VET: '📡',
  FIL: '🗃️',
  THETA: '🎯',
  EOS: '💎',
  BCH: '🪙',
  BSV: '🪙',
  WBTC: '🪙',
  DAI: '💰',
  TUSD: '💵',
  BUSD: '💵',
  PAXG: '🥇',
};

export function getTokenEmoji(symbol: string): string {
  const upperSymbol = symbol.toUpperCase();
  return TOKEN_EMOJI_MAP[upperSymbol] || '🪙'; // Default emoji
}

